### ISSUE TITLE
Deployment on Celo

### ISSUE THREAD

**Issue by Metachaser24** [ethereum-attestation-service/eas-contracts#106]
Hi. we are very excited about the impact that EAS can have in the web3 ecosystem. We would love for you guys to deploy on Celo as my company Cr3dentials, GainForest, and Impact Market are looking to build on top of it. 

Thanks so much

**Comment by daviddao** [comment]
+1 supporting the deployment of EAS to Celo. We believe the Celo community and infrastructure would benefit from a deployment, potentially helping to advance attestations for the land registries, environment, credit scores and more.

**Comment by positonic** [comment]
I support this, and would build on it immediately.

**Comment by Abhimanyu121** [comment]
Yes, I too need it to be on Celo.

**Comment by lopeselio** [comment]
Much needed. We’re building a ReFi centric game on Celo, and would be cool to have this feature

**Comment by UziQidwai** [comment]
Yes please!

**Comment by patricknbaron** [comment]
This would be useful for a lot of applications built on Celo.

**Comment by lbeder** [comment]
We will be more than happy to support Celo as soon as it migrates. Stay tuned!

**Comment by daviddao** [comment]
What's the timeline? Can we reopen the issue until it's deployed?

**Comment by lbeder** [comment]
We are waiting to see when Celo finishing its migration to the OP Stack

**Comment by daviddao** [comment]
Why? Celo is already EVM compatible and the L2 transition wouldn't change anything at all in the dev experience.

**Comment by lbeder** [comment]
Supporting the current Celo deployment will require plenty of changes on our app/backend side, which will have to be redone after Celo's migration to L2. We are already stretched thin 🙏

**Comment by daviddao** [comment]
Hey guys, great work with https://github.com/ethereum-attestation-service/eas-contracts/commit/ed74d3e20a22473aa5e53353c1e5c568953e57e8
