### ISSUE TITLE
attestation.data (un-)packing

### ISSUE THREAD

**Issue by Caruso33** [ethereum-attestation-service/eas-contracts#113]
Hi,

not directly an issue but maybe something to add:

Is there any example how to pack and unpack the attestation.data field?

For example I was trying to add more data to the attest call and use this info in a resolver to call other smart contracts.

https://github.com/Caruso33/Calimocho/blob/7d0485051d3d4c7b2a25f25f1ad5b35db3164fc2/eas-contracts/contracts/CalimochoResolver.sol#L42

Unfortunately, I never got this to run. I think others would also benefit from an example.

Thank you,

Tobias

**Comment by lbeder** [comment]
Hi @Caruso33,
We don't presuppose how the data should be parsed, so it's totally up to you. We do generally recommend encode/decode it as ABI, which you can find for example here: https://github.com/ethereum-attestation-service/eas-contracts-example/blob/master/contracts/ExampleUintResolver.sol

**Comment by Caruso33** [comment]
Thanks 🙏🏼 that was the hint I was hoping for. 

Somehow I must have overlooked the UintResolver Example.
