### ISSUE TITLE
Unclear how to code schema & attest with multiple schema fields

### ISSUE THREAD

**Issue by divine-comedian** [ethereum-attestation-service/eas-contracts#124]
Hi there! I'm having a hard time processing your documentation to understand my scenario for registering a schema & then attesting with it. Currently there is no documentation for: 
- Registering a schema using only solidity
- Creating an attestation for a schema that requires multiple fields

I'm currently running a foundry project and creating the schema and making the attestations directly from solidity for the purposes of testing. I would like to register a schema that has multiple fields, these are: 

- address[] addresses
- string[] memory strings
- uint256[] numbers

so from here is this how I would encode my schema fields and register a new schema? 

```
    string schema = "address[] participants, string[] memory vows, uint256[] ringIds";
        schemaRegistry = new SchemaRegistry();
        easContract = new EAS(ISchemaRegistry(address(schemaRegistry)));
      // we want to limit who can use this schema - we set the attester to another address later on...
        attesterResolver = new AttesterResolver(IEAS(address(easContract)), address(this));
       bytes32 schemaUID = schemaRegistry.register(schema, ISchemaResolver(address(attesterResolver)), true);

//  setting the attester in an admin function     
   attesterResolver.setTargetAttester(address(contractApprovedToAttest));
```

the `register` function in the schemaRegistry contract requires the schema to be of type `string callData` 

maybe I'm a n00b and doing this all wrong, but if that looks good then to attest we call from the approved attester contract:

```
function someFunction() {
           bytes32 uid = easContract.attest(
            AttestationRequest({
                schema: schema,
                data: AttestationRequestData({
                    recipient: union.participants[0],
                    expirationTime: NO_EXPIRATION_TIME,
                    revocable: true,
                    refUID: EMPTY_UID,
                    data: abi.encode(addresses, strings, numbers),
                    value: 0
                })
            })
        );
}
```

Do we need to format the data a certain way or do we plug in the variables in the respective order? 

Sorry if this is the wrong place, Twitter support hasn't been very helpful and I think the documentation can be improved to make this case easier to understand and code.

**Comment by lbeder** [comment]
Hi @divine-comedian,

Regarding the registration of the schema, your code looks totally fine (you can pass `memory` to a function which receives `calldata`). Keep in mind that the `data` field of the attestation isn't decoded automatically, and it's in the responsibility of the resolver, so you might need to build a custom resolver (building on top of one of the sample resolvers). You can also find more examples here: https://github.com/ethereum-attestation-service/eas-contracts-example

We don't have a twitter support, so I hope that you weren't speaking with a scammer account. 

Please don't hesitate to ask more questions on our Telegram channel: https://t.me/+EcynOr0iFu03MTYx
