### ISSUE TITLE
Attestation did not verify whether the format of the `data` matches the `schema`.

### ISSUE THREAD

**Issue by yjshi2015** [ethereum-attestation-service/eas-contracts#135]
```
function _attest(
        bytes32 schemaUID,
        AttestationRequestData[] memory data,
        address attester,
        uint256 availableValue,
        bool last
    ) private returns (AttestationsResult memory) {
            // ...

            Attestation memory attestation = Attestation({
                uid: EMPTY_UID,
                schema: schemaUID,
                refUID: request.refUID,
                time: _time(),
                expirationTime: request.expirationTime,
                revocationTime: 0,
                recipient: request.recipient,
                attester: attester,
                revocable: request.revocable,
                // There is no verification of its format here, it can be any data!
                data: request.data
            });

          // ...
    }
```

This `data` attribute can be any value because it is in bytes format. Maybe an attacker can interact with the EAS contract directly instead of through the `EAS SDK` or `EASScan Website`, so he can pass any data, **even data that does not match the schema**, which is very bad, so I think it is also possible in the EAS contract Verification of data should be added to determine whether it matches the schema.

**Comment by lbeder** [comment]
EAS doesn't presuppose anything, so the schema itself can be anything and not necessarily an ABI specification; therefore we can't perform any of these validations. If extra validation is desired, we recommend doing this in the resolver itself.

**Comment by yjshi2015** [comment]
> EAS doesn't presuppose anything, so the schema itself can be anything and not necessarily an ABI specification; therefore we can't perform any of these validations. If extra validation is desired, we recommend doing this in the resolver itself.

Yes, this does provide a lot of flexibility, but it may bring problems on the other hand. For example, we create a reputation system, but the reputation system is maliciously written into some non-standard data, that is, Dirty data (somewhat similar to a DOS attack), will this reduce everyone's trust in this reputation system?

**Comment by lbeder** [comment]
But this is irrelevant to the format of the data itself. I.e., if you allow everyone to submit trust scores for users - format verification won't really help you because anyone could still fake the data using the "correct" format. 

In any case, this type of verification should be done on the app layer, and we can't force any format nor validate it.

**Comment by yjshi2015** [comment]
I get it, Thx~
