### ISSUE TITLE
Support Batch Registration in `SchemaRegistry.sol`

### ISSUE THREAD

**Issue by YamenMerhi** [ethereum-attestation-service/eas-contracts#137]
## Description

The **SchemaRegistry** contains a function to register a schema. This function is able to handle 1 schema on call.

There could be some scenarios where registration of multiple schemas is beneficial, for instance on deployment in the repo, a **registration is triggered for 30+ schemas**, where each registration happens as a standalone transaction. 

I don't see any harm in adding a new function that accepts a batch, an array of the existing parameters, by wrapping the existing function in a for loop, and doing the necessary checks. It will save a lot of gas for people willing to register several schemas at once, saving a fixed 21,000 gas on each tx, which makes it worth considering a `registerBatch` function.

Compatibility with old versions available by keeping the register function, and adding a `registerBatch` function.

```js

 /// @inheritdoc ISchemaRegistry
    function registerBatch(string[] calldata schemas, ISchemaResolver[] calldata resolvers, bool[] calldata revocables) external returns (bytes32[] memory) {
        require(schemas.length == resolvers.length && resolvers.length == revocables.length, "Array lengths must be equal");
        require(schemas.length == 0, "Array lengths must be greater than 0");

        bytes32[] memory uids = new bytes32[](schemas.length);

        for (uint i = 0; i < schemas.length; i++) {
            SchemaRecord memory schemaRecord = SchemaRecord({
                uid: EMPTY_UID,
                schema: schemas[i],
                resolver: resolvers[i],
                revocable: revocables[i]
            });

            bytes32 uid = _getUID(schemaRecord);
            if (_registry[uid].uid != EMPTY_UID) {
                revert AlreadyExists();
            }

            schemaRecord.uid = uid;
            _registry[uid] = schemaRecord;

            emit Registered(uid, msg.sender, schemaRecord);
            uids[i] = uid;
        }

        return uids;
    }
```

which then can be used in the deployment script, to make it cheaper + faster.

Same thing should apply to attestation, in the deployment script, would be good if `multiAttest` can be used instead of `attest`, would also save time and cost.
https://github.com/ethereum-attestation-service/eas-contracts/blob/296eabae070f11772ee373c0652eaea025098f4a/deploy/scripts/000004-name-initial-schemas.ts#L18-L33

Happy to discuss further. 🙏

**Comment by lbeder** [comment]
Hi @YamenMerhi,

Thank you for your suggestions. We are currently prioritizing other developments and since batch schema registration optimizes for a rare use case, we will definitely consider implementing this in the future, although in a slightly lower priority.
