### ISSUE TITLE
Deploy schemaRegistry to Amoy

### ISSUE THREAD

**Issue by JustinFeng** [ethereum-attestation-service/eas-contracts#140]
Polygon Mumbai is going to be deprecated, any plan to deploy the EAS contracts to the successor network Amoy?

**Comment by lbeder** [comment]
Yeah, it's on the roadmap

**Comment by iPaulPro** [comment]
> Yeah, it's on the roadmap

Is there a timeline available? It's the only testnet for Polygon PoS so any details are greatly appreciated. 🙏

**Comment by iPaulPro** [comment]
ping @lbeder

**Comment by lbeder** [comment]
Hey @iPaulPro, we are currently preoccupied with another mainnet deployment, so as soon as we'll finish - we'll move on to this 🙏

**Comment by lbeder** [comment]
Apparently EAS already existed there (since it was a fork of Mumbai), but I've documented it properly here: https://github.com/ethereum-attestation-service/eas-contracts/pull/143

**Comment by iPaulPro** [comment]
> Apparently EAS already existed there (since it was a fork of Mumbai), but I've documented it properly here: #143

Amoy is a sidechain to Sepolia; a totally new network, not a fork of Mumbai (which was a sidechain to Goerli). There are no contracts deployed at the addresses now linked from that PR.

https://amoy.polygonscan.com/address/0xaEF4103A04090071165F78D45D83A0C0782c2B2a
https://amoy.polygonscan.com/address/0x55D26f9ae0203EF95494AE4C170eD35f4Cf77797

**Comment by lbeder** [comment]
Ah, that's weird... I probably checked Mumbai by accident

**Comment by lbeder** [comment]
Take #2 😅 : https://github.com/ethereum-attestation-service/eas-contracts/pull/144
