### ISSUE TITLE
CSS loading issue with EAS website

### ISSUE THREAD

**Issue by 0xScratch** [ethereum-attestation-service/eas-contracts#147]
There seems an issue within the EAS site, the landing page doesn't load up correctly. Here's the screenshot:

![Screenshot (109)](https://github.com/user-attachments/assets/afc766cb-a498-4a2a-b490-0adf5794e7f1)

Whereas, docs are working fine (shows that there isn't even a network problem):

![Screenshot (110)](https://github.com/user-attachments/assets/d9d797ec-2a91-4f56-8669-7b8b47dabede)

**Comment by lbeder** [comment]
Could be a cache or a local issue, since it seems to work here correctly. In any case, it's not a contract issue, so resolving.
