### ISSUE TITLE
IEAS.sol should be Solidity ^0.8.0 but Common.sol breaks it

### ISSUE THREAD

**Issue by smartcontracts** [ethereum-attestation-service/eas-contracts#57]
The [IEAS.sol](https://github.com/ethereum-attestation-service/eas-contracts/blob/master/contracts/IEAS.sol) interface file is marked as Solidity ^0.8.0 but imports [Common.sol](https://github.com/ethereum-attestation-service/eas-contracts/blob/master/contracts/Common.sol) which is Solidity 0.8.15. Solidity compiler therefore forces any contracts importing IEAS.sol to use 0.8.15 which breaks anything that wants to use a different version of Solidity 0.8.

**Comment by lbeder** [comment]
Nice catch! On it.

**Comment by lbeder** [comment]
Fixed in afa1c2a

**Comment by smartcontracts** [comment]
Thank you!
