### ISSUE TITLE
UI suggestion (tiny one) 

### ISSUE THREAD

**Issue by bobjiang** [ethereum-attestation-service/eas-contracts#59]
after I created an attestation, here is a link "offchain link" which is clickable. 
but nothing happened when clicking

I suggest to copy the link when clicking "Offchain link"

<img width="252" alt="image" src="https://github.com/ethereum-attestation-service/eas-contracts/assets/1224604/232109da-0f05-4100-85fd-dbcec3a116f9">

**Comment by slavik0329** [comment]
@bobjiang Great suggestion! This fix has been pushed to production
