### ISSUE TITLE
When will you deploy on Optimism Mainnet?

### ISSUE THREAD

**Issue by Chomtana** [ethereum-attestation-service/eas-contracts#62]
We need to launch our product in a few days on Optimism Mainnet, and our product depends on EAS. When will you deploy on Optimism Mainnet? Or can we deploy it on our own?

However, I don't think deterministic deployment will be a problem for users as they usually use UI not directly interact with the smart contract.  The developer is responsible for testing their code properly. However, it's still a problem for code upgrades.

**Comment by lbeder** [comment]
Hey @Chomtana,
We are actually planning to deploy on Optimism Mainnet in the next couple of days, so stay tuned 😎

**Comment by lbeder** [comment]
Done and done 😎

**Comment by Chomtana** [comment]
Feel like possible redeployment due to #64 and #65?

**Comment by lbeder** [comment]
Potentially, yeah. We are currently working on this with Optimism's team.

**Comment by Chomtana** [comment]
In case of a contract upgrade, if the attestation is done on the old contract, what will happen in the explorer? It will show the old data or not show it at all?

**Comment by lbeder** [comment]
Yeah, definitely. If an upgradeable variant of EAS is deployed, the explorer will always show any attestations made using the previous implementaation.
