### ISSUE TITLE
Offchain attestation "Attestation failed resolver check"

### ISSUE THREAD

**Issue by Chomtana** [ethereum-attestation-service/eas-contracts#76]
<img width="1410" alt="image" src="https://github.com/ethereum-attestation-service/eas-contracts/assets/4103490/2c1c3734-373f-4852-bfe5-ce48f3f7f3df">

Hello world off-chain attestation from https://optimism-goerli-bedrock.easscan.org/

https://optimism-goerli-bedrock.easscan.org/offchain/url/#attestation=eNqlkcltJDEMRXOpc8EgKa7HavdEMfCB1BKAMQM4fKs6AgP%2BOoiAqMfl%2Fz3wDd7wOJngPOBrXz8Q7Q872VajVo0XYaYrNI3OSqsVLYsuO29WqOuOAMby%2FdKHIBVUcsYLQiKgy2bPkjZrzLEoR2gGKKm1HCaYM5RqqNLQNsRhsE5BcZvHSXZzfAvxem%2FPd0Aln48nUeGVgNnESfIZYdNfRRNHagts0LGmt7GsC3LuTmYDoXLzjXAs9qyazWMW4titii3IF6SFRhWYZl8VQbmE7%2BmMu3TfYzP2lMY893r6gMIlk5dDdnCi9YIswOcAlEdnpuFGZHJZVPT843zpWvGgi%2Bw4UQPc9gr4vK06zn%2Bf%2F%2BeNgF%2BJ4Jeq22Dt%2BywCs%2B0l7Zh%2FDjj2PPjxDaSXmOo%3D

**Comment by slavik0329** [comment]
Ah yes this is a bug on our end just in OP goerli. Will fix this ASAP and update you

**Comment by slavik0329** [comment]
@Chomtana This should now be fixed! Please try again and let me know if it's still an issue.
