### ISSUE TITLE
ENS subdomain not working?

### ISSUE THREAD

**Issue by Chomtana** [ethereum-attestation-service/eas-contracts#77]
![image](https://github.com/ethereum-attestation-service/eas-contracts/assets/4103490/279d8577-6590-421e-9246-6446f344ea46)

![image](https://github.com/ethereum-attestation-service/eas-contracts/assets/4103490/41485ffe-c134-4234-b589-a9d614486ed5)

I have set the domain name of 0x888811A117405f323BabfB415c6D61F678e967dA to oracle.optidomains.eth but EAS doesn't detect the domain name. Probably EAS subdomain is not working.

EAS: https://optimism.easscan.org/address/0x888811A117405f323BabfB415c6D61F678e967dA
Etherscan: https://etherscan.io/address/0x888811A117405f323BabfB415c6D61F678e967dA

**Comment by slavik0329** [comment]
It was simply cached. To refresh cache you can use the forceEnsUpdate flag. It should be all good now!

https://optimism.easscan.org/address/0x888811A117405f323BabfB415c6D61F678e967dA?forceEnsUpdate=true
