### ISSUE TITLE
Deployment in polygon

### ISSUE THREAD

**Issue by irux** [ethereum-attestation-service/eas-contracts#79]
Hello! we are a web3 startup and we would like to integrate all the documents signing with eas. Any reason why this is not in polygon yet ? I would love to deploy it :)

**Comment by lbeder** [comment]
Hey @irux,
We are planning to deploy to Polygon, but currently focusing on finalizing some new features. 

Stay tuned!

**Comment by irux** [comment]
amazing @lbeder ! any way I can help? I think it would be amazing if you guys create a discord!

**Comment by lbeder** [comment]
It'd be great to test the new version on Polygon's testnet (but let's wait for everything to finalize first).

**Comment by irux** [comment]
Any news on this @lbeder ? Do you have a discord for the community?

**Comment by slavik0329** [comment]
> Any news on this @lbeder ? Do you have a discord for the community?

@irux EAS has been deployed to polygon and polygon testnet. https://polygon.easscan.org/

**Comment by irux** [comment]
@slavik0329 do you guys have a discord or something to connect with others? Share use cases or questions?

**Comment by slavik0329** [comment]
> @slavik0329 do you guys have a discord or something to connect with others? Share use cases or questions?

Yes, we have a telegram channel: https://t.me/+BCuSb4rgoeg2N2Zh

**Comment by michael-spengler** [comment]
... great ... https://github.com/ethereum-attestation-service/eas-contracts/blob/master/README.md#polygon 

Next Potential Challenge: How about Polygon zkEVM (the most promising / up to date Polygon chain imo - correct me if I'm wrong) https://chainlist.org/chain/1101

**Comment by lbeder** [comment]
Polygon zkEVM will require further adaptions, but it's definitely on the roadmap.
