### ISSUE TITLE
Error: Unknown Signer for account

### ISSUE THREAD

**Issue by 0xYudhishthra** [ethereum-attestation-service/eas-contracts#84]
gm! I'm trying to deploy EAS to Arbitrum Goerli but keep receiving this error `Error: Unknown Signer for account:`

In the .env, I used the value of a wallet address as the DEPLOYER variable

I've updated the relevant files to reflect deploying to the testnet, but still facing this error. Would like to know what step I've missed in deploying it. Thanks :)

**Comment by lbeder** [comment]
Hey @0xYudhishthra,
This is probably due to some missing `.env` parameters, but no worries - we have just deployed the latest version on Arbitrum Goerli

**Comment by 0xYudhishthra** [comment]
Would it also be possible to deploy this to the Avalanche C-Chain Testnet? Thanks!

**Comment by lbeder** [comment]
We are already stretched pretty thin, so we currently don't have any plans to officially support Avalanche C-Chain Testnet or Mainnet 😢. Of course, everyone can deploy EAS to Avalanche, it's just that we won't be able to support and update eascan, the SDK, the documentation, etc.

**Comment by 0xYudhishthra** [comment]
No worries on that ser! Asked cause for the dApp I'm building, I'd like to deploy it on the C Chain testnet too and since I can't do it because of missing `.env` variables, was hoping if you could help me out

**Comment by lbeder** [comment]
I hope to find some time to help you with this 🙏

**Comment by avivash** [comment]
hey @0xYudhishthra 👋🏼 did you ever get around the `Unknown Signer for account` error? I assume it's because the tx can't get automatically signed the EOA address(metamask in my case) I'm using as the `DEPLOYER` 🤔
